### PR TITLE
Add a single-line code golf example

### PR DESCRIPTION
**Pull request by bmistree**
I enjoyed your talk today. Here's my 1-line version of the word frequency counting program. A couple of notes: 
  1) I hard-coded the file that the program operates over. If I took the file as a command line argument, I know this would work in 2 lines, and there still may be a weird way to get it to work in one
  2) If it'd be helpful, I'd be happy to create an alternate version that's split into several files/functions to explain what the code is actually doing.

Please let me know what you think. Thanks!

### CODE REVIEW

**Comment by bmistree** [comment]
Just wanted to follow up on the first point above (hard-coding the file that the program operates over): I *think* I can keep this as a single line program *and* take in the filename as a command line argument if I use __import__ in a weird way. Let me know if you want me to give that a shot. Thanks again!

**Comment by crista** [comment]
hahaha. Very cool!
Wanna try getting the file name from the command line? As is, it's already hard enough to understand, so another trick won't matter much!

**Comment by bmistree** [comment]
I think that this change should take the filename as a program arg. It also makes it so that you can execute the script from any directory. This was fun, let me know if you think any other changes would be helpful. Thanks again!

**Comment by crista** [comment]
Cool! :+1: 
People will enjoy seeing this.

**Pull request merged**
